# Generated by Django 5.2.8 on 2026-05-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_likes',
            name='post_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='network.post'),
        ),
    ]
